//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolioProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Experience
    {
        public int ExperienceID { get; set; }
        public string WorkplaceName { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
    }
}
